version: '3'
services:
  uaa:
    image: darilliumgalaxy/uaa:latest
    depends_on: 
    - mysql
    env_file:
    - .env
    ports:
    - 8080:8080
    volumes:
    - ./config:/config
  mysql:
    image: mysql/mysql-server:5.7.8 
    env_file:
    - .env
    ports:
    - 3306:3306
  mongodb:
    image: mongo:latest
    ports:
    - 27017:27017
  asgard:
    image: darilliumgalaxy/asgard:latest 
    ports:
    - 9090:9090
    